service: spotify-now-playing-app

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  profile: spotify-now-playing-${self:custom.stage}
  environment:
    APP_BUCKET_NAME: nowplaying.tinyrobot.co

resources:
  Resources:
    AppBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.APP_BUCKET_NAME}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html