org: akhtarja
app: spotify-now-playing
service: spotify-now-playing-playback-state

plugins:
  - PlaybackStateDeploymentPlugin
  - serverless-pseudo-parameters

custom:
  namespace: spotify-now-playing-${self:custom.stage}
  stage: ${opt:stage, self:provider.stage}
  config_path: "../app/js/config"

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  profile: spotify-now-playing-${self:custom.stage}
  environment:
    SPOTIFY_CLIENT_ID: ${env:SPOTIFY_NOW_PLAYING_CLIENT_ID_${self:custom.stage}}
    SPOTIFY_CLIENT_SECRET: ${env:SPOTIFY_NOW_PLAYING_CLIENT_SECRET_${self:custom.stage}}
    SPOTIFY_NOW_PLAYING_CUSTOM_ENDPOINT_URL: ${env:SPOTIFY_NOW_PLAYING_CUSTOM_ENDPOINT_URL}
    USERS_TABLE: ${self:custom.namespace}-users
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource:
        arn:aws:dynamodb:*:*:table/${self:provider.environment.USERS_TABLE}

functions:
  playbackState:
    name: ${self:custom.namespace}-playback-state
    handler: handler.playbackState
    onError: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:spotify-now-playing-dlq-${self:custom.stage}-dlq
    events:
      - http:
          path: playbackstate
          method: get
